[package]
name = "notebook"
version = "0.1.0"
authors = ["betta-cyber <l21828604@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.11.0"
log = "0.4"
wasm-bindgen = "0.2"
failure = "0.1.6"
