# Favicon
favicon: /favicon.ico

# SEO
keywords: betta-cyber, game, betta, shokill

# Site title separator
separator: "-"

# RSS
rss: /atom.xml

# SNS config
sns:
  Blog: /blog
  GitHub: https://github.com/betta-cyber
  Zhihu: https://www.zhihu.com/people/ShoKill
  Steam: https://steamcommunity.com/id/betta551/
  # Douban: https://www.douban.com/people/beita502/

# Nav menu
menu:
  Home: /
  Blog: /blog
  Ebook: /ebook
  Music: /music
  Photo: /album
  About: /about

code:
  lang: true # 代码块是否显示名称
  copy: true # 代码块是否可复制
  shrink: true # 代码块是否可以收缩
  break: false # 代码是否折行
