name: github pages

on:
  push:
    branches:
    - dev

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm ci
    - run: npm install
    - run: npm install font-spider -g
    - run: npm run build
    - run: sed -i 's/\/css\/style.css/..\/css\/style.css/g' `grep ".html" -rl public`
    - run: font-spider --ignore public/music_rym/* "public/!(page)**/*.html" --debug
    - run: sed -i 's/..\/css\/style.css/\/css\/style.css/g' `grep ".html" -rl public`
    - run: cp -rf source/music_rym public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
